version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_service
    command: uvicorn app_api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - app-network

  streamlit:
    build: .
    container_name: streamlit_service
    command: streamlit run streamlit_app.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
